### ISSUE TITLE
Add VPC-specific block syntax

### ISSUE THREAD

**Issue by swissChili** [quiverteam/QuiverProjectCreator#1]
Add the following syntax to QPC's parser:
```c
foo bar
{
    // baz
}
```
> Note: this is not valid KeyValues syntax, but rather: is VPC specific

Currently, to achieve a similar result something like this mus be done:
```c
foo
{
    name bar
    // baz
}
```

If this is to be implemented the following needs to be done:

- [x] Change KeyValues parser to accept this format
- [ ] Re think build scripts to utilize this new syntax

**Comment by Demez** [comment]
I think it should be added, while using `name blah` is fine, it's unnecessary imo, and it can make scripts slightly longer

using client_hl2r.vpc as an example
![2019-06-18_17-12-45_Discord_#quiver-project-creator_-_Discord](https://user-images.githubusercontent.com/30940677/59720815-c6cb4e00-91ed-11e9-8d17-847182be1d6b.png)

if we used the KeyValues syntax, we would get this:
```
Folder
{
    name "Source Files"

    File "hud_chat.cpp"
    File "c_team_objectiveresource.cpp"
    File "c_team_objectiveresource.h"

    Folder
    {
        name "HL2R DLL"
        
        File "hl2r/c_hl2r_flashlighteffect.cpp"
        File "hl2r/c_hl2r_flashlighteffect.h"
    }

    Folder
    {
        name "HL2 DLL"

        File	"hl2\c_basehlplayer.cpp"
        File	"hl2\c_basehlplayer.h"
    }
}
```
